'use client';

import { useEffect, useState } from 'react';
import AddDoctorModal from '@/app/components/AddDoctorModal'; 
import API from '@/services/api';

export default function AdminDoctorsPage() {
  const [doctors, setDoctors] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  
  const [expandedDocId, setExpandedDocId] = useState<string | null>(null);

  useEffect(() => {
    fetchDoctors();
  }, []);

  const fetchDoctors = async () => {
    try {
      setLoading(true);
    
      const response = await API.get('/doctor');
      
      setDoctors(response.data); 
    } catch (err) {
      console.error('Failed to fetch doctors:', err);
    } finally {
      setLoading(false);
    }
  };

  const toggleExpand = (id: string) => {
    setExpandedDocId(expandedDocId === id ? null : id);
  };

  return (
    <div className="w-full">

      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <h1 className="text-gray-800 font-serif text-lg md:text-xl">
          total number of Doctors : {loading ? '...' : doctors.length}
        </h1>
        
        <button 
          onClick={() => setIsModalOpen(true)}
          className="bg-[#126b8a] hover:bg-[#0e566f] text-white text-sm md:text-base py-2.5 px-6 rounded-full transition-colors shadow-sm whitespace-nowrap"
        >
          Add Doctors
        </button>
      </div>

      <div className="hidden md:block w-full border-[2px] border-gray-300 rounded-[20px] overflow-hidden shadow-sm bg-white">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[600px] text-center border-collapse">
            <thead>
              <tr className="border-b-[2px] border-gray-300 bg-white">
                <th className="py-6 px-4 font-serif text-gray-800 font-normal border-r border-gray-300 w-1/5">Name</th>
                <th className="py-6 px-4 font-serif text-gray-800 font-normal border-r border-gray-300 w-1/5">Specialization</th>
                <th className="py-6 px-4 font-serif text-gray-800 font-normal border-r border-gray-300 w-1/5">Email</th>
                <th className="py-6 px-4 font-serif text-gray-800 font-normal border-r border-gray-300 w-1/5">Working Hour</th>
                <th className="py-6 px-4 font-serif text-gray-800 font-normal w-1/5">Time Zone</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan={4} className="py-12 text-gray-400">Loading doctors...</td></tr>
              ) : doctors.length === 0 ? (
                <tr><td colSpan={4} className="py-12 text-gray-400">No doctors found.</td></tr>
              ) : (
                doctors.map((doctor) => (
                  // Uses _id generated by Mongoose
                  <tr key={doctor._id} className="border-b border-gray-200 last:border-b-0 ">
                    <td className="py-10 px-4 text-gray-700 border-r border-gray-300">{doctor.name}</td>
                    <td className="py-10 px-4 text-gray-700 border-r border-gray-300">{doctor.specialization}</td>
                    <td className="py-10 px-4 text-gray-700 border-r border-gray-300">{doctor.email}</td>
                    <td className="py-10 px-4 text-gray-700 border-r border-gray-300">{doctor.startTime} - {doctor.endTime}</td>
                    <td className="py-10 px-4 text-gray-700">{doctor.timeZone}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      <div className="md:hidden flex flex-col gap-3">
        {loading ? (
          <div className="p-6 text-center text-gray-400 border-[2px] border-gray-300 rounded-[20px] bg-white">
            Loading doctors...
          </div>
        ) : doctors.length === 0 ? (
          <div className="p-6 text-center text-gray-400 border-[2px] border-gray-300 rounded-[20px] bg-white">
            No doctors found.
          </div>
        ) : (
          doctors.map((doctor) => (
            <div 
              key={doctor._id} 
              className="border-[2px] border-gray-300 rounded-[16px] overflow-hidden bg-white shadow-sm transition-all duration-300"
            >
              <button 
                onClick={() => toggleExpand(doctor._id)}
                className="w-full flex justify-between items-center p-5 bg-white hover:bg-gray-50 focus:outline-none"
              >
                <span className="font-serif text-lg text-gray-800">{doctor.name}</span>

                <div className={`transform transition-transform duration-300 text-gray-500 ${expandedDocId === doctor._id ? 'rotate-180' : ''}`}>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-5 h-5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                  </svg>
                </div>
              </button>

              <div 
                className={`transition-all duration-300 ease-in-out ${
                  expandedDocId === doctor._id ? 'max-h-64 opacity-100' : 'max-h-0 opacity-0'
                }`}
              >
                <div className="p-5 border-t border-gray-200 bg-gray-50 flex flex-col gap-3 text-[15px]">
                  <div className="flex justify-between border-b border-gray-200 pb-2">
                    <span className="text-gray-500">Specialization</span>
                    <span className="font-medium text-gray-800">{doctor.specialization}</span>
                  </div>
                  <div className="flex justify-between border-b border-gray-200 pb-2">
                    <span className="text-gray-500">Email</span>
                    <span className="font-medium text-gray-800">{doctor.email}</span>
                  </div>
                  <div className="flex justify-between border-b border-gray-200 pb-2">
                    <span className="text-gray-500">Working Hours</span>
                    <span className="font-medium text-gray-800">{doctor.startTime} - {doctor.endTime}</span>
                  </div>
                  <div className="flex justify-between pb-1">
                    <span className="text-gray-500">Time Zone</span>
                    <span className="font-medium text-gray-800">{doctor.timeZone}</span>
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      <AddDoctorModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)} 
        onSuccess={fetchDoctors} 
      />

    </div>
  );
}